{% set name = "gnucobol" %}
{% set version = "3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/{{ name }}/{{ name }}-{{ version }}.tar.xz
  sha256: 3bb48af46ced4779facf41fdc2ee60e4ccb86eaa99d010b36685315df39c2ee2

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - pkg-config
    - make
    - gettext-tools
  host:
    - gmp
    - json-c
    - libxml2
    - ncurses
    - libdb
    - libintl-devel  # [not linux]
  run:
    - {{ c_compiler }}_{{ target_platform }}

test:
  commands:
    - cobc --version
    - {{ RECIPE_DIR }}/test.sh

about:
  home: https://www.gnu.org/software/gnucobol/
  summary: COBOL85-202x compiler supporting lots of dialect specific extensions
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  doc_url: https://gnucobol.sourceforge.io/guides.html

extra:
  recipe-maintainers:
    - pavelzw
